// export const users = [
//               {
//                 "uid": "user_1",
//                 "fullName": "Mehwish Khan",
//                 "email": "mehwish.khan2025@gmail.com",
//                 "phone": "03200000001",
//                 "gender": "Female",
//                 "age": "24",
//                 "bId": "biz_1",
//                 "photoURL": "https://randomuser.me/api/portraits/women/21.jpg"
//               },
//               {
//                 "uid": "user_2",
//                 "fullName": "Nazia Arif",
//                 "email": "nazia.arif2025@gmail.com",
//                 "phone": "03200000002",
//                 "gender": "Female",
//                 "age": "25",
//                 "bId": "biz_2",
//                 "photoURL": "https://randomuser.me/api/portraits/women/22.jpg"
//               },
//               {
//                 "uid": "user_3",
//                 "fullName": "Rabia Saleem",
//                 "email": "rabia.saleem2025@gmail.com",
//                 "phone": "03200000003",
//                 "gender": "Female",
//                 "age": "26",
//                 "bId": "biz_3",
//                 "photoURL": "https://randomuser.me/api/portraits/women/23.jpg"
//               },
//               {
//                 "uid": "user_4",
//                 "fullName": "Neha Kamal",
//                 "email": "neha.kamal2025@gmail.com",
//                 "phone": "03200000004",
//                 "gender": "Female",
//                 "age": "27",
//                 "bId": "biz_4",
//                 "photoURL": "https://randomuser.me/api/portraits/women/24.jpg"
//               },
//               {
//                 "uid": "user_5",
//                 "fullName": "Tania Javed",
//                 "email": "tania.javed2025@gmail.com",
//                 "phone": "03200000005",
//                 "gender": "Female",
//                 "age": "28",
//                 "bId": "biz_5",
//                 "photoURL": "https://randomuser.me/api/portraits/women/25.jpg"
//               },
//               {
//                 "uid": "user_6",
//                 "fullName": "Maliha Shah",
//                 "email": "maliha.shah2025@gmail.com",
//                 "phone": "03200000006",
//                 "gender": "Female",
//                 "age": "29",
//                 "bId": "biz_6",
//                 "photoURL": "https://randomuser.me/api/portraits/women/26.jpg"
//               },
//               {
//                 "uid": "user_7",
//                 "fullName": "Zoya Yousaf",
//                 "email": "zoya.yousaf2025@gmail.com",
//                 "phone": "03200000007",
//                 "gender": "Female",
//                 "age": "30",
//                 "bId": "biz_7",
//                 "photoURL": "https://randomuser.me/api/portraits/women/27.jpg"
//               },
//               {
//                 "uid": "user_8",
//                 "fullName": "Amna Riaz",
//                 "email": "amna.riaz2025@gmail.com",
//                 "phone": "03200000008",
//                 "gender": "Female",
//                 "age": "31",
//                 "bId": "biz_8",
//                 "photoURL": "https://randomuser.me/api/portraits/women/28.jpg"
//               },
//               {
//                 "uid": "user_9",
//                 "fullName": "Sadia Noreen",
//                 "email": "sadia.noreen2025@gmail.com",
//                 "phone": "03200000009",
//                 "gender": "Female",
//                 "age": "32",
//                 "bId": "biz_9",
//                 "photoURL": "https://randomuser.me/api/portraits/women/29.jpg"
//               },
//               {
//                 "uid": "user_10",
//                 "fullName": "Fariha Murtaza",
//                 "email": "fariha.murtaza2025@gmail.com",
//                 "phone": "03200000010",
//                 "gender": "Female",
//                 "age": "33",
//                 "bId": "biz_10",
//                 "photoURL": "https://randomuser.me/api/portraits/women/30.jpg"
//               },
//               {
//                 "uid": "user_11",
//                 "fullName": "Tariq Jameel",
//                 "email": "tariq.jameel2025@gmail.com",
//                 "phone": "03200000011",
//                 "gender": "Male",
//                 "age": "24",
//                 "bId": "biz_11",
//                 "photoURL": "https://randomuser.me/api/portraits/men/21.jpg"
//               },
//               {
//                 "uid": "user_12",
//                 "fullName": "Imran Nazir",
//                 "email": "imran.nazir2025@gmail.com",
//                 "phone": "03200000012",
//                 "gender": "Male",
//                 "age": "25",
//                 "bId": "biz_12",
//                 "photoURL": "https://randomuser.me/api/portraits/men/22.jpg"
//               },
//               {
//                 "uid": "user_13",
//                 "fullName": "Kamil Sohail",
//                 "email": "kamil.sohail2025@gmail.com",
//                 "phone": "03200000013",
//                 "gender": "Male",
//                 "age": "26",
//                 "bId": "biz_13",
//                 "photoURL": "https://randomuser.me/api/portraits/men/23.jpg"
//               },
//               {
//                 "uid": "user_14",
//                 "fullName": "Salman Rafiq",
//                 "email": "salman.rafiq2025@gmail.com",
//                 "phone": "03200000014",
//                 "gender": "Male",
//                 "age": "27",
//                 "bId": "biz_14",
//                 "photoURL": "https://randomuser.me/api/portraits/men/24.jpg"
//               },
//               {
//                 "uid": "user_15",
//                 "fullName": "Junaid Khan",
//                 "email": "junaid.khan2025@gmail.com",
//                 "phone": "03200000015",
//                 "gender": "Male",
//                 "age": "28",
//                 "bId": "biz_15",
//                 "photoURL": "https://randomuser.me/api/portraits/men/25.jpg"
//               },
//               {
//                 "uid": "user_16",
//                 "fullName": "Haroon Shahid",
//                 "email": "haroon.shahid2025@gmail.com",
//                 "phone": "03200000016",
//                 "gender": "Male",
//                 "age": "29",
//                 "bId": "biz_16",
//                 "photoURL": "https://randomuser.me/api/portraits/men/26.jpg"
//               },
//               {
//                 "uid": "user_17",
//                 "fullName": "Zeeshan Tariq",
//                 "email": "zeeshan.tariq2025@gmail.com",
//                 "phone": "03200000017",
//                 "gender": "Male",
//                 "age": "30",
//                 "bId": "biz_17",
//                 "photoURL": "https://randomuser.me/api/portraits/men/27.jpg"
//               },
//               {
//                 "uid": "user_18",
//                 "fullName": "Noman Qadir",
//                 "email": "noman.qadir2025@gmail.com",
//                 "phone": "03200000018",
//                 "gender": "Male",
//                 "age": "31",
//                 "bId": "biz_18",
//                 "photoURL": "https://randomuser.me/api/portraits/men/28.jpg"
//               },
//               {
//                 "uid": "user_19",
//                 "fullName": "Asad Farooq",
//                 "email": "asad.farooq2025@gmail.com",
//                 "phone": "03200000019",
//                 "gender": "Male",
//                 "age": "32",
//                 "bId": "biz_19",
//                 "photoURL": "https://randomuser.me/api/portraits/men/29.jpg"
//               },
//               {
//                 "uid": "user_20",
//                 "fullName": "Waleed Zafar",
//                 "email": "waleed.zafar2025@gmail.com",
//                 "phone": "03200000020",
//                 "gender": "Male",
//                 "age": "33",
//                 "bId": "biz_20",
//                 "photoURL": "https://randomuser.me/api/portraits/men/30.jpg"
//               }
//             ]

//             export const tailors = [
//               {
//                 "approved": true,
//                 "ownerId": "user_1",
//                 "businessName": "StyleCrafters Studio",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000001",
//                 "businessPictureUrl": "/images/profile/business/business-1.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Where creativity meets tradition. We deliver tailor-made outfits for women, kids, and special events with utmost care.",
//                 "experience": "4",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_2",
//                 "businessName": "Threaded Charm",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000002",
//                 "businessPictureUrl": "/images/profile/business/business-2.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Focusing on quality men's and kids' tailoring, we offer detailed fittings and contemporary designs for everyday and event wear.",
//                 "experience": "5",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_3",
//                 "businessName": "Stitch Artisan",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000003",
//                 "businessPictureUrl": "/images/profile/business/business-3.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Design-centric tailoring house crafting bespoke dresses for ladies with finesse, creativity, and flair for fashion.",
//                 "experience": "6",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Kids Specialist",
//                   "Women Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_4",
//                 "businessName": "Prestige Stitchworks",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000004",
//                 "businessPictureUrl": "/images/profile/business/business-4.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Modern tailoring tailored for all ages, providing premium quality with quick turnaround for all types of garments.",
//                 "experience": "7",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Kids Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_5",
//                 "businessName": "Zoya\u2019s Ethnic Wardrobe",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000005",
//                 "businessPictureUrl": "/images/profile/business/business-5.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Specialists in ethnic wear for kids and women with stylish cuts and traditional flair. Hand-embroidery available on request.",
//                 "experience": "8",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Custom Tailoring",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_6",
//                 "businessName": "Cut & Sew Lounge",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000006",
//                 "businessPictureUrl": "/images/profile/business/business-6.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "We help shape your style dreams into wearable art\u2014our tailors work on every detail to create standout garments.",
//                 "experience": "9",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_7",
//                 "businessName": "Moda Tailors",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000007",
//                 "businessPictureUrl": "/images/profile/business/business-7.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Quality tailoring for men who value comfort and elegance. We cater to formal, casual, and ethnic wear.",
//                 "experience": "10",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_8",
//                 "businessName": "StitchXpress",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000008",
//                 "businessPictureUrl": "/images/profile/business/business-8.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "A trusted name for alteration and premium tailoring, with modern tools and legacy stitching expertise.",
//                 "experience": "11",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Kids Specialist",
//                   "Women Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_9",
//                 "businessName": "Fashion Weave Hub",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000009",
//                 "businessPictureUrl": "/images/profile/business/business-9.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "We bring life to fabrics with artistic tailoring for men and women, from festive wear to daily ensembles.",
//                 "experience": "4",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Kids Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_10",
//                 "businessName": "Graceful Threads",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000010",
//                 "businessPictureUrl": "/images/profile/business/business-10.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Known for graceful fits and elegant lines, we customize garments for both kids and women in your desired fashion.",
//                 "experience": "5",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Custom Tailoring",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_11",
//                 "businessName": "Nimble Needleworks",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000011",
//                 "businessPictureUrl": "/images/profile/business/business-11.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "A luxury tailoring boutique focused on creating signature styles with precision, especially for bridal and party wear.",
//                 "experience": "6",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_12",
//                 "businessName": "Stitchery Elite",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000012",
//                 "businessPictureUrl": "/images/profile/business/business-12.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Versatile tailoring services with modern approach, crafting wearables that fit your lifestyle and personality.",
//                 "experience": "7",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_13",
//                 "businessName": "Custom Threadworks",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000013",
//                 "businessPictureUrl": "/images/profile/business/business-13.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Where detail matters\u2014we provide elegant and crisp tailoring for men\u2019s and kids\u2019 fashion needs.",
//                 "experience": "8",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Kids Specialist",
//                   "Women Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_14",
//                 "businessName": "Artisan Stitch House",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000014",
//                 "businessPictureUrl": "/images/profile/business/business-14.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Kids\u2019 clothing specialists offering creative styling and comfortable stitching to suit growing minds and bodies.",
//                 "experience": "9",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Kids Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_15",
//                 "businessName": "Classic Weaves",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000015",
//                 "businessPictureUrl": "/images/profile/business/business-15.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Delivering perfection through threads\u2014our boutique is best for festive tailoring and made-to-measure creations.",
//                 "experience": "10",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Custom Tailoring",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_16",
//                 "businessName": "Wardrobe Tailor Co.",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000016",
//                 "businessPictureUrl": "/images/profile/business/business-16.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Expert tailors for grooms and professionals offering structured suits and sleek finishes in minimal time.",
//                 "experience": "11",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_17",
//                 "businessName": "TailorWorx Studio",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000017",
//                 "businessPictureUrl": "/images/profile/business/business-17.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Women\u2019s exclusive tailoring boutique balancing vintage vibes and contemporary couture effortlessly.",
//                 "experience": "4",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Alterations",
//                   "Custom Tailoring"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_18",
//                 "businessName": "SewFine Apparel",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000018",
//                 "businessPictureUrl": "/images/profile/business/business-18.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Ethnic tailoring for the modern age\u2014custom fitting services with embroidery, lining, and unique finishes.",
//                 "experience": "5",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Kids Specialist",
//                   "Women Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_19",
//                 "businessName": "Golden Touch Fashions",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000019",
//                 "businessPictureUrl": "/images/profile/business/business-19.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "A creative tailoring house for men and women specializing in fabric selection, style consultations, and stitching.",
//                 "experience": "6",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Men Specialist",
//                   "Kids Specialist",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               },
//               {
//                 "approved": true,
//                 "ownerId": "user_20",
//                 "businessName": "Fine Threads Studio",
//                 "businessAddress": "Islamabad, Pakistan",
//                 "businessPhone": "03200000020",
//                 "businessPictureUrl": "/images/profile/business/business-20.jpg",
//                 "closeTime": "18:00",
//                 "countryCode": "+92",
//                 "description": "Custom, elegant, and detail-oriented\u2014we are redefining clothing through curated tailoring services.",
//                 "experience": "7",
//                 "lastUpdated": "2025-04-30T14:00:00.000Z",
//                 "openTime": "10:00",
//                 "rating": 0,
//                 "specialities": [
//                   "Women Specialist",
//                   "Custom Tailoring",
//                   "Alterations"
//                 ],
//                 "status": "active",
//                 "total_rating": 0
//               }
//             ]
          